POST http://localhost:3000/api/v1/mentors/
content-type: application/json

{  
    "photo": "true",
    "fullName": "Mentor 10",
    "title": "Prashanga's test",
    "description": "I love testing"
} 